### ISSUE TITLE
Question about async loading

### ISSUE THREAD

**Issue by sarunast** [njosefbeck/gatsby-plugin-stripe#1]
I was wondering why are not using the async loading as described in here:
https://github.com/stripe/react-stripe-elements#loading-stripejs-asynchronously

**Comment by sarunast** [comment]
Nevermind I see that there is more work to it. But maybe it would be great to enable this by passing some kind of configurations?

**Comment by njosefbeck** [comment]
This is a great feature idea - to allow a user to specify if they want the script to load asynchronously. I'm going to re-open this, and add this feature to the CHANGELOG so I can keep track. Thanks for bringing this to my attention!

**Comment by njosefbeck** [comment]
@sarunast This is now implemented and published to npm: https://www.npmjs.com/package/gatsby-plugin-stripe

Let me know if you experience any issues with using the feature! Thanks!

**Comment by delanebob** [comment]
@njosefbeck would it be possible to also add an option for adding an "id" to the script tag?

You can see in the example code [here](https://github.com/stripe/react-stripe-elements#loading-stripejs-asynchronously), it specifies to add an "id" to the script tag so we can listen for when it's loaded.

**Comment by njosefbeck** [comment]
@delanebob - I've added an id to the script tag and published the update to NPM. I didn't make it an option, but I made the id the same as what's found in that example code you linked. Thanks for the suggestion!
