### ISSUE TITLE
SSR issue when using react-stripe-elements

### ISSUE THREAD

**Issue by buzzguy** [njosefbeck/gatsby-plugin-stripe#2]
Hi, Works great when I'm developing locally, but once I try building or pushing to production on netlify, it looks for the window and breaks before it renders. Is there a best way to do this using this plugin? thanks!

I get this error:
`Error: Please pass either 'apiKey' or 'stripe' to StripeProvider. If you're using 'stripe' but don't have a Stripe instance yet, pass 'null' explicitly.``Error: Please pass either 'apiKey' or 'stripe' to StripeProvider. If you're using 'stripe' but don't have a Stripe instance yet, pass 'null' explicitly.`

And I've tried:
``````
import React, { useState, useEffect } from "react";
import { Link } from "gatsby";
import { Elements, StripeProvider } from "react-stripe-elements";
import CheckoutForm from "../components/CheckoutForm";
import Layout from "../components/Layout";
const CheckoutPage = () => {
  const [stripe, setStripe] = useState(null);
  useEffect(() => {
      setStripe(window.Stripe(process.env.STRIPE_PUBLISHABLE_KEY));
  });
  return (
    <Layout>
      <Link to="/">back</Link>!<h1>Checkout Page</h1>
      <StripeProvider stripe={stripe}>
        <Elements>
          <CheckoutForm />
        </Elements>
      </StripeProvider>
    </Layout>
  );
};

export default CheckoutPage;

``````

**Comment by njosefbeck** [comment]
Hello!

Two thoughts: 
(1) [Per the docs](https://github.com/stripe/react-stripe-elements#then-load-stripejs-in-your-application) it looks like you can just pass the API key to `<StripeProvider>` instead of the stripe object. Have you tried that?

(2) Before the line with `const [stripe, setStripe] = useState(null)` you could add a check for window, and return early if it's not there.

Let me know if either of those work for you!

**Comment by buzzguy** [comment]
Hi there!

I was using apiKey originally which was working great, but that's where I found the original issue when I tried publishing.

original
```
const CheckoutPage = () => {

  return (
    <Layout>
      <Link to="/">back</Link>!<h1>Checkout Page</h1>
      <StripeProvider apiKey={process.env.STRIPE_PUBLISHABLE_KEY}>
        <Elements>
          <CheckoutForm />
        </Elements>
      </StripeProvider>
    </Layout>
  );
};

export default CheckoutPage;
```

and get this error:
``` 
ERROR #95312
"window" is not available during server side rendering.
See our docs page for more info on this error: https://gatsby.dev/debug-html
ReferenceError: window is not defined
```

I also did try another version of checking for window in useEffect like:
```
const CheckoutPage = () => {
  const [stripe, setStripe] = useState(null);
  useEffect(() => {
    // for SSR
    if (typeof window === "undefined") return;

    // for browser
    if (window.Stripe) {
      setStripe(window.Stripe(process.env.STRIPE_PUBLISHABLE_KEY));
    } else {
      const stripeScript = document.querySelector("#stripe-js");
      stripeScript.onload = () => {
        setStripe(window.Stripe(process.env.STRIPE_PUBLISHABLE_KEY));
      };
    }
  }, []);
  return (
    <Layout>
      <Link to="/">back</Link>!<h1>Checkout Page</h1>
      <StripeProvider stripe={stripe}>
        <Elements>
          <CheckoutForm />
        </Elements>
      </StripeProvider>
    </Layout>
  );
};

export default CheckoutPage;
```
which returns the same error and I just tested adding a check for window, but returns the error about needing either an apiKey or stripe obj as well

```
const CheckoutPage = () => {
  if (typeof window === "undefined") {
    return null;
  }
  return (
    <Layout>
      <Link to="/">back</Link>!<h1>Checkout Page</h1>
      <StripeProvider apiKey={process.env.STRIPE_PUBLISHABLE_KEY}>
        <Elements>
          <CheckoutForm />
        </Elements>
      </StripeProvider>
    </Layout>
  );
};
```

**Comment by njosefbeck** [comment]
Hmm, so it looks like you're doing things properly as per the `react-stripe-elements` docs... one question: you are setting that STRIPE_PUBLISHABLE_KEY in Netlify right? So that Netlify has access to it.

Also, it looks like there's a webpack customization you could try: https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules

**Comment by buzzguy** [comment]
yea, I have those in already, set in the build & deploy section. 

thanks, I'll try those fixes from the docs!

**Comment by njosefbeck** [comment]
Sounds good! Yeah let me know when you figure out a solution, and I can update the docs here as well to include it :).

**Comment by buzzguy** [comment]
oi vey, thanks for helping out. After I installed loadable, and still saw the issue, I thought maybe you were right about the STRIPE_PUBLISHABLE_KEY. 
I found out the issue, forgot to add `'NODE_ENV':'production'` in netlify, and now it works!

**Comment by njosefbeck** [comment]
Ohh, well I'm glad that you were able to figure it out! Gonna close this issue, but if you ever run into any other issues, don't hesitate to reach out 👍

**Comment by buzzguy** [comment]
Correcting myself, I was trying a lot of different things last week and what I didn't realize is that you need to prefix any env keys with `GATSBY_` for it to work. So the fix was to use `GATSBY_STRIPE_PUBLISHABLE_KEY` instead of STRIPE_PUBLISHABLE_KEY, and adding that gatsby prefixed key in your netlify admin
